/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-02 08:00:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/Documents/workspace-spring-tool-suite-4-4.7.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portfolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1594169636771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/user/signup\">\r\n");
      out.write("    <div class=\"page\">\r\n");
      out.write("        <div class=\"noti-wrap\">\r\n");
      out.write("            <p>회원정보 입력</p>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div class=\"container-info\">\r\n");
      out.write("                <div class=\"box-info\">\r\n");
      out.write("                    <div class=\"box-inputForm\" id=\"id\">\r\n");
      out.write("                        <strong>아이디</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"아이디를 입력하세요\" name = \"id\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <label for=\"\" id=\"id-error\" class=\"error\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\">\r\n");
      out.write("                        <strong>비밀번호</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"password\"  placeholder=\"영문,숫자 8자리 이상\"  name=\"pw\" id=\"pw\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <label id=\"pw-error\" class=\"error\" for=\"pw\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\">\r\n");
      out.write("                        <strong>비밀번호 확인</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"password\"  placeholder=\"비밀번호를 재입력하세요\" name=\"pw2\" id=\"pw2\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <label id=\"pw2-error\" class=\"error\" for=\"pw2\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\">\r\n");
      out.write("                        <strong>이메일</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"email\" placeholder=\"이메일을 입력하세요\" name=\"email\" id=\"email\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <label id=\"email-error\" class=\"error\" for=\"email\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\" id=\"year\">\r\n");
      out.write("                        <strong>출생년도</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"text\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\" id=\"month\">\r\n");
      out.write("                        <strong>월</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <select name=\"month\" id=\"month\">\r\n");
      out.write("                                <option value=\"1\">선택</option>\r\n");
      out.write("                                <option value=\"1\">1</option>\r\n");
      out.write("                                <option value=\"2\">2</option>\r\n");
      out.write("                                <option value=\"3\">3</option>\r\n");
      out.write("                                <option value=\"4\">4</option>\r\n");
      out.write("                                <option value=\"5\">5</option>\r\n");
      out.write("                                <option value=\"6\">6</option>\r\n");
      out.write("                                <option value=\"7\">7</option>\r\n");
      out.write("                                <option value=\"8\">8</option>\r\n");
      out.write("                                <option value=\"9\">9</option>\r\n");
      out.write("                                <option value=\"10\">10</option>\r\n");
      out.write("                                <option value=\"11\">11</option>\r\n");
      out.write("                                <option value=\"12\">12</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\" id=\"day\">\r\n");
      out.write("                        <strong>일</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"text\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\">\r\n");
      out.write("                        <strong>성별</strong>\r\n");
      out.write("                        <span class=\"radio-wrap\">\r\n");
      out.write("                            <span class=\"custom-radio\">\r\n");
      out.write("                                <input type=\"radio\" class=\"#\">여자\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"radio-wrap\">\r\n");
      out.write("                            <span class=\"custom-radio\">\r\n");
      out.write("                                <input type=\"radio\" class=\"#\">남자\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-inputForm\" id=\"phone\">\r\n");
      out.write("                        <strong>휴대전화</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"tel\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn-send\">인증번호 발송</a>\r\n");
      out.write("                    <div class=\"box-inputForm\">\r\n");
      out.write("                        <strong>인증번호</strong>\r\n");
      out.write("                        <span class=\"box-label\">\r\n");
      out.write("                            <input type=\"email\"  placeholder=\"인증번호를 입력하세요\">\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"box-limit\">\r\n");
      out.write("                        <button class=\"btn btn-normal\">인증번호 재발송</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"btns col1\">\r\n");
      out.write("                <button class=\"btnL btn-ready\">회원가입</button>\r\n");
      out.write("            </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('input[name=id]').keyup(function(){ //keyup:글자가 눌릴때마다\r\n");
      out.write("\t\t\tvar id = $(this).val();\r\n");
      out.write("\t\t\tif(id.length >= 3){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t        async:true,\r\n");
      out.write("\t\t\t        type:'POST',\r\n");
      out.write("\t\t\t        data:id,\r\n");
      out.write("\t\t\t        url:\"");
      out.print(request.getContextPath());
      out.write("/idCheck\",\r\n");
      out.write("\t\t\t        dataType:\"json\",\r\n");
      out.write("\t\t\t        contentType:\"application/json; charset=UTF-8\",\r\n");
      out.write("\t\t\t        success : function(data){\r\n");
      out.write("\t\t\t\t        var str;\r\n");
      out.write("\t\t\t            if(data['res']){\r\n");
      out.write("\t\t\t\t            str = \r\n");
      out.write("\t\t\t\t\t        '<p style=\"color:green;\">사용 가능한 아아디입니다.</p>'\r\n");
      out.write("\t\t\t            }else{\r\n");
      out.write("\t\t\t            \tstr = \r\n");
      out.write("\t\t\t\t\t        '<p style=\"color:red;\">이미 사용중이거나 탈퇴한 아이디입니다.</p>'\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t            $('#id-error').html(str);\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif(id.length == 0)\r\n");
      out.write("\t\t\t\t\t$('#id-error').html('필수 항목입니다.');\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t$('#id-error').html('아이디는 세글자 이상이어야 합니다.');\r\n");
      out.write("\t\t\t}  \r\n");
      out.write("\t\t})\r\n");
      out.write("        $(\"form\").validate({\r\n");
      out.write("            rules: {\r\n");
      out.write("                pw: {\r\n");
      out.write("                    required : true,\r\n");
      out.write("                    minlength : 8,\r\n");
      out.write("                    regex: /^(?=\\w{8,20}$)\\w*(\\d[A-z]|[A-z]\\d)\\w*$/\r\n");
      out.write("                },\r\n");
      out.write("                pw2: {\r\n");
      out.write("                    required : true,\r\n");
      out.write("                    minlength : 8,\r\n");
      out.write("                    equalTo : pw\r\n");
      out.write("                },\r\n");
      out.write("\r\n");
      out.write("                email: {\r\n");
      out.write("                    required : true,\r\n");
      out.write("                    email : true\r\n");
      out.write("                },\r\n");
      out.write("                gender: {\r\n");
      out.write("\t            \trequired : true\r\n");
      out.write("\t            }\r\n");
      out.write("            },\r\n");
      out.write("            //규칙체크 실패시 출력될 메시지\r\n");
      out.write("            messages : {\r\n");
      out.write("                pw: {\r\n");
      out.write("                    required : \"필수로입력하세요\",\r\n");
      out.write("                    minlength : \"최소 {0}글자이상이어야 합니다\",\r\n");
      out.write("                    regex : \"영문자, 숫자로 이루어져있으며 최소 하나이상 포함\"\r\n");
      out.write("                },\r\n");
      out.write("                pw2: {\r\n");
      out.write("                    required : \"필수로입력하세요\",\r\n");
      out.write("                    minlength : \"최소 {0}글자이상이어야 합니다\",\r\n");
      out.write("                    equalTo : \"비밀번호가 일치하지 않습니다.\"\r\n");
      out.write("                },\r\n");
      out.write("                email: {\r\n");
      out.write("                    required : \"필수로입력하세요\",\r\n");
      out.write("                    email : \"메일규칙에 어긋납니다\"\r\n");
      out.write("                },\r\n");
      out.write("                gender: {\r\n");
      out.write("                    required: \"필수로 입력하세요\"\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $.validator.addMethod(\r\n");
      out.write("        \t    \"regex\",\r\n");
      out.write("        \t    function(value, element, regexp) {\r\n");
      out.write("        \t        var re = new RegExp(regexp);\r\n");
      out.write("        \t        return this.optional(element) || re.test(value);\r\n");
      out.write("        \t    },\r\n");
      out.write("        \t    \"Please check your input.\"\r\n");
      out.write("        \t);\r\n");
      out.write("\t})\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
